pipeline {
  agent any
  tools { 
        maven 'maven_3_5_2'  
    }
   stages{
    stage('Build'){
            steps{
            sh 'mvn install'      
            }
    }
    stage('UnitTest'){
            steps{
            sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
    }
    stage('CompileandRunSonarAnalysis') {
            steps {	
	    sh 'mvn clean verify sonar:sonar -Dsonar.projectKey=devsecops_assignment-sast -Dsonar.organization=anuja2015devsecOps -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=credentials('SONAR_TOKEN')'
			}
        }
    stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    stage('Last Stage'){
            steps{
                echo 'Job Completed!!'
            }
        } 
 }
 
  
}